version: "3"
services:
  neo4j:
    image: 'neo4j:4.1.0-enterprise'
    ports:
      - ${NEO4J_PORT-7474}:7474
      - ${NEO4J_BOLT_PORT-7687}:7687
      - ${NEO4J_JMX_PORT-3637}:3637
    environment:
      NEO4J_AUTH: ${NEO4J_AUTH-neo4j/test123}
      NEO4J_ACCEPT_LICENSE_AGREEMENT: 'yes'
      NEO4JLABS_PLUGINS: "[\"apoc\"]"
    healthcheck:
      test: ["CMD", "wget", "--spider", "0.0.0.0:7474"]
      interval: 10s
      timeout: 10s
      retries: 10
    volumes:
      - ../neo4j/conf:/conf
