addSbtPlugin("com.typesafe.sbt" % "sbt-git"      % "1.0.2")
addSbtPlugin("ch.epfl.scala"    % "sbt-bloop"    % "1.4.9")
addSbtPlugin("org.xerial.sbt"   % "sbt-sonatype" % "3.9.10")
addSbtPlugin("com.jsuereth"     % "sbt-pgp"      % "2.1.1")
addSbtPlugin("au.com.onegeek"  %% "sbt-dotenv"   % "2.1.233")
addSbtPlugin("ch.epfl.scala"    % "sbt-scalafix" % "0.10.0")
addSbtPlugin("org.scalameta"    % "sbt-scalafmt" % "2.4.3")
addSbtPlugin("com.github.sbt"   % "sbt-release"   % "1.3.0")