addSbtPlugin("com.typesafe.sbt" % "sbt-git"      % "1.0.0")
addSbtPlugin("ch.epfl.scala"    % "sbt-bloop"    % "1.4.7")
addSbtPlugin("org.xerial.sbt"   % "sbt-sonatype" % "3.9.5")
addSbtPlugin("com.jsuereth"     % "sbt-pgp"      % "2.0.2")
addSbtPlugin("au.com.onegeek"  %% "sbt-dotenv"   % "2.1.233")
addSbtPlugin("org.scalameta"    % "sbt-scalafmt" % "2.4.2")
