name: Scala CI - Test

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Compile
      run: sbt ";compile ;test:compile"
    
    - name: Run tests (no Neo4j)
      run: sbt "testOnly * -- -l com.arkondata.slothql.test.tags.RequiresNeo4j"
      
    - name: Setup Neo4j
      uses: fehu/Setup-Neo4j@v1.2.0
      with:
        password: neo4j

    - name: Wait for Neo4j to startup
      uses: nev7n/wait_for_response@v1.0.1
      with:
        url: localhost:7474
        timeout: 30000
        interval: 1000
    
    - name: Run tests (with Neo4j)
      run: sbt "testOnly * -- -n com.arkondata.slothql.test.tags.RequiresNeo4j"
