name: Scala CI - Test

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  test:

    runs-on: ubuntu-latest

    services:
      neo4j:
        image: 'neo4j:4.1.0-enterprise'
        env:
          NEO4J_AUTH: 'neo4j/test'
          NEO4JLABS_PLUGINS: ['apoc']
        ports: 
          - 7474:7474
          - 7687:7687
        options: --health-cmd "wget --quiet --spider localhost:7474" --health-interval 100s --health-timeout 100s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Compile
      run: sbt ";compile ;test:compile"

    - name: Run tests (require Neo4j with APOC plugin)
      env:
        NEO4J_HOST: 'localhost'
        NEO4J_AUTH: 'neo4j/test'
      run: sbt test
