name: Scala CI - Test

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  test:

    runs-on: ubuntu-latest

    services:
      neo4j:
        image: neo4j:latest
        env:
          NEO4J_AUTH: 'neo4j/test'
        ports: 
          - 7474:7474
          - 7687:7687
        options: |
          --health-cmd "wget --quiet --spider localhost:7474"
          --health-interval 20s
          --health-timeout 10s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Compile
      run: sbt ";compile ;test:compile"
    
    - name: Run tests (not require Neo4j)
      run: sbt "testOnly * -- -l com.arkondata.slothql.test.tags.RequiresNeo4j"
      
    - name: Run tests (require Neo4j)
      run: sbt "testOnly * -- -n com.arkondata.slothql.test.tags.RequiresNeo4j"
